### ISSUE TITLE
Add trade routes

### ISSUE THREAD

**Issue by silsha** [wneessen/sotbot#17]
It would be good if we can query the weekly trade routes via the bot. The website does not publish them, but rarethief keeps them updated on the map.

* Rarethief map: https://maps.seaofthieves.rarethief.com/
* JS including the current trade routes: https://ddc5e4l4zgom9.cloudfront.net/js/trade_routes.js

**Comment by wneessen** [comment]
Could you suggest a format in how the routes should be presented by the bot?

**Comment by silsha** [comment]
Maybe these Discord Embed elements would be suitable for this, but I don't know how many key/value pairs you can specify there.

Otherwise, maybe like this:

> 
> **Sanctuary**: Sought after: _Spices_ / Surplus: _Gemsontes_
> **Golden Sands**: Sought after: _Tea_ / Surplus: _Stones_
> …

It would be even better if you could generate an image with the map. But that could be too cumbersome.
