### ISSUE TITLE
If there is no credit change in a session, the last diff is displayed.

### ISSUE THREAD

**Issue by silsha** [wneessen/sotbot#28]
As you can see in the screenshot, I made -8063 gold on 6.6. Then on 9.6. I logged in twice briefly to test something without my balance changing. The bot then told me again that I had made -8063 gold.

<img width="1194" alt="PNG image" src="https://user-images.githubusercontent.com/31850/121686237-344ea400-cac1-11eb-9f31-1abd5a3dd267.png">

**Comment by wneessen** [comment]
Fixed
