### ISSUE TITLE
Output more stats after the session

### ISSUE THREAD

**Issue by silsha** [wneessen/sotbot#29]
After the session, the bot could output additional information _if it has changed_:

* Sunk ships
* Megalodon encounters
* Number of vomits
* Number of chests redeemed
* Kraken defeated

**Comment by wneessen** [comment]
https://github.com/wneessen/sotbot/tree/v1.4.5-issue_29 is ready for testing. It works for me, but I wasn't able to test the mixed announcement of stats and balance changes yet (as I haven't had the time to play and earn some money).

I've also removed the announce_user_dm feature as I found it intrusive and useless.

**Comment by silsha** [comment]
Thanks, I'll use this version and watch for problems.

**Comment by wneessen** [comment]
I've merged it to the main branch together with your PR now.
