### ISSUE TITLE
Use slash commands

### ISSUE THREAD

**Issue by silsha** [wneessen/sotbot#30]
We have several bots which respond to !help or !play for example. Discord now offers real slash commands:
https://discord.com/developers/docs/interactions/slash-commands

**Comment by wneessen** [comment]
Slash command are in planning. Unfortunately the Discord API is constantly changing which keeps the discordgo guys from releasing that feature. Once it's available those will be coming

**Comment by wneessen** [comment]
First tests look promissing
![image](https://user-images.githubusercontent.com/542696/121861245-f5eff980-ccf9-11eb-906c-6c15d3d4c724.png)

**Comment by wneessen** [comment]
The https://github.com/wneessen/sotbot/tree/slash_cmds branch now support slash commands. Please check the "permissions.png" in the README.md, as the bot requires additional permission for the slash commands to work. You'll probably have to remove and re-join the bot on your server for it to work. Also keep in mind, that slash commands are cached and may take up 1h to appear.

**Comment by wneessen** [comment]
For now the !help, !version and !play commands have been transformed into slash commands.

**Comment by wneessen** [comment]
So far the following commands have been converted in that branch:

- !help
- !version
- !play
- !dailydeed
- !achievement
- !balance
- !reputation
- !ledger
- !stats

More to come. Feel free to give it some proper testing

**Comment by wneessen** [comment]
All commands have been converted to slash commands. Let's test a bit more until I'll merge it into main
