### ISSUE TITLE
Better handling of incomplete commands

### ISSUE THREAD

**Issue by silsha** [wneessen/sotbot#31]
If you type `!rep`, you will get the response: 
> Unknown command. See !help for more information.

If you type `!rep bla`, you get:
> Incorrect request format. Usage: !reputation <athena|bilge|hoarder|hunter|merchant|order|reaper|seadog>

I would expect to get the second output as well if you type `!rep`.

The same applies to all commands which need an additional parameter.

**Comment by wneessen** [comment]
Fixed

**Comment by wneessen** [comment]
(At least I hope... was only able to verify it works if the balance didn't change, but not if the balance actually changed)
