### ISSUE TITLE
No balance change reported after session

### ISSUE THREAD

**Issue by silsha** [wneessen/sotbot#33]
After my session with a friend yesterday, I did not receive a notification, while my friend did. I should have received a credit change in any case, since I bought a wood crate. Here are the relevant log outputs:

```
DEBUG[2021-06-11 19:53:15 +0200] silsha started playing SoT. Updating balance...  action=bot.UserPlaySot
DEBUG[2021-06-11 19:53:15 +0200] Fetching balance from API...                  action=sotapi.GetBalance
DEBUG[2021-06-11 19:53:16 +0200] Balance has changed. Updating and storing history entry
DEBUG[2021-06-11 19:55:38 +0200] silsha started playing SoT. Updating balance...  action=bot.UserPlaySot
DEBUG[2021-06-11 19:55:38 +0200] Fetching balance from API...                  action=sotapi.GetBalance
DEBUG[2021-06-11 19:55:39 +0200] Balance didn't change since last check. Skipping update
DEBUG[2021-06-11 20:31:46 +0200] silsha stopped playing SoT. Updating balance...  action=bot.UserPlaySot
DEBUG[2021-06-11 20:31:46 +0200] Fetching balance from API...                  action=sotapi.GetBalance
DEBUG[2021-06-11 20:31:47 +0200] Balance didn't change since last check. Skipping update
```

I'll be monitoring this a little longer to see if the problem reoccurs.

**Comment by wneessen** [comment]
I've seen this before. Sometimes the API is very slow in reflecting the value changes, especially when the servers are busy. Monitoring sounds good.

**Comment by silsha** [comment]
I just had the situation where I received a message after the session. I then logged in again for a short time (without changing the credit balance) and immediately received another message.

It looks like the API is a bit behind. Maybe it makes sense to wait a few minutes after the session before sending the results.

That way you could also avoid getting the message when the game has crashed but the session is not over yet.

Translated with www.DeepL.com/Translator (free version)

![grafik](https://user-images.githubusercontent.com/31850/121804187-68eb6880-cc45-11eb-8a34-13edf18c1fb5.png)
