### ISSUE TITLE
Nicer output for SoT auto-track feature

### ISSUE THREAD

**Issue by wneessen** [wneessen/sotbot#39]
After a SoT playing session, the bot reports the changes to balance and stats, even if some of the values are 0. This clutters the output and doesn't look nice. Any zero value should be omitted in the output instead.

**Comment by silsha** [comment]
Quick mockup I made in [Discord Embed Generator](https://cog-creators.github.io/discord-embed-sandbox/).

![grafik](https://user-images.githubusercontent.com/31850/122066707-439c5d00-cdf3-11eb-9ddd-7b296fb1cd86.png)

We don't use Python, but here you can copy out the texts and emojis if you want:
```
embed=discord.Embed(title="Trip Summary for @silsha")
embed.add_field(name="🟡 Gold", value="📈 200,000 Gold", inline=True)
embed.add_field(name="🔵 Doubloons", value="📈 1,000 Doubloons", inline=True)
embed.add_field(name="💰Ancient Coins", value="📉 2,123 Coins", inline=True)
embed.add_field(name="🐙 Kraken", value="3 defeated", inline=True)
embed.add_field(name="🦈 Megalodon", value="4 encountered", inline=True)
embed.add_field(name="🎁 Chests", value="62 sold", inline=True)
embed.add_field(name="⛵️Ships", value="6 sank", inline=True)
embed.add_field(name="🤮 Vomitted", value="3 times", inline=True)
await ctx.send(embed=embed)
```

**Comment by wneessen** [comment]
Progress was made
![image](https://user-images.githubusercontent.com/542696/122225436-5b3c1a00-ceb5-11eb-895f-03f464a3898f.png)

**Comment by wneessen** [comment]
`/status` needs a revamp as well.
