### ISSUE TITLE
/setrat crashes discord client

### ISSUE THREAD

**Issue by wneessen** [wneessen/sotbot#41]
On some clients, using the `/setrat` command in combination with pasting the very long cookie, crashes the discord client. An alternative !setrat (revieval) is needed as alternative

**Comment by silsha** [comment]
Discord seems to have a problem if you use parameters with too many underscores. I have opened a ticket with Discord.

Reproducible with this parameter:
`_A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A__A_`

**Comment by wneessen** [comment]
Although this is a Discord bug, the `!setrat` command is back as alternative
